### PR TITLE
new version

### PR DESCRIPTION
**Pull request by mattiabress**
I updated your code using the new version of Nokia library, i added also new feature. 
It is possible to manage the error better

### CODE REVIEW

**Comment by yohhoy** [comment]
Wow! Thanks for your large PR.

But, could you change following topics?
- remove `heic2hevc` executable file
- remove `.idea` directory
- remove media files (`*.heic` and `*.265`)
- remove `example.cpp` (if the file is not necessary for this project)
- and squash to single commit

**Comment by mattiabress** [comment]
Yes. Sure, I do it.
Thank you for your advices

**Comment by yohhoy** [comment]
I checked the code diff in PR again, and there are so many changes that it is essentially your work (copyright).

This repo was my personal tiny project, and I don't have a plan to maintenance this project any more.

So I suggest you that;
* close this PR.
* add link to your repository in README (and I archive this repo.)

**Comment by mattiabress** [comment]
All right, 
what should I do? Should I remove my fork and create another repository? 

Thank you for advices

**Comment by yohhoy** [comment]
> Should I remove my fork and create another repository?

No, no.
You may continue to use forked [your repository](https://github.com/mattiabress/heic2hevc), or create another ones.

**Pull request closed without merging**
